name: Cache
on:
  workflow_dispatch:
jobs:
  build:
    name: Build with cache job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Java and cache
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
    - name: Build project
      run: ./gradlew build --no-daemon
